### PR TITLE
Update FINOS badge on README.MD to INCUBATING

### PR DESCRIPTION
**Pull request by mcleo-d**
This pull request communicates the repo status as INCUBATING in accordance with project materials recorded and tracked at FINOS.

### CODE REVIEW

**Comment by mcleo-d** [comment]
@jonfreedman - Yesterday I applied the ARCHIVED badge to this project where the actual status is INCUBATING.

The next step is for the team minute and agree whether the project is ACTIVE with a simple vote, which I'm more than happy to help coordinate.

**Comment by jonfreedman** [comment]
James the project was the first active project back when finos was the symphony software foundation, its certainly not incubating. 


As I've said to Mao previously, the only reason the project would not be archived is if Symphony customers are still using it, and they will know the answer to that. 


Just don't archive the project in GitHub itself as then it's proper read only


Cheers 


Jon 




---- On Fri, 20 Dec 2019 15:18:40 +0000 notifications@github.com wrote ----



@jonfreedman - Yesterday I applied the ARCHIVED badge to this project where the actual status is INCUBATING.

The next step is for the team minute and agree whether the project is ACTIVE with a simple vote, which I'm more than happy to help coordinate.

**Comment by mcleo-d** [comment]
Hi @jonfreedman,

I can confirm this is a project status update only and we're not physically archiving the project on GitHub. This will not affect the communities ability to raise pull requests or raise issues.

My objective is to take the project team back through the FINOS project lifecycle so we can apply the new ACTIVE state to the project. This just means having simple team vote on the ACTIVE status.

We can do this very fast and even as a GitHub issue to vote on. In the meantime, it would be great if you could accept the PR so the badge reflects the INCUBATING status as we move to ACTIVE.

I hope this helps?

James.

**Comment by mcleo-d** [comment]
@jonfreedman 

I have raised an issue for the activation vote below that formally takes the project from INCUBATING to ACTIVE.

https://github.com/symphonyoss/hubot-symphony/issues/86

James.

**Pull request merged**
